name: vehicle
description: "Cyber1 TMS - Terminal Management System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.5
  intl: ^0.19.0
  uuid: ^4.4.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
